name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Testcontainers
        run: |
          sudo service docker start
          docker info

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24'

      - name: Install Ginkgo
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo

      - name: Run tests
        run: /home/runner/go/bin/ginkgo -r

      - name: Generate coverage report
        run: go test -coverprofile="coverage.txt" $(go list ./... | grep -v '/examples\|/mock')

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}