name: Codecov

on:
  push:
    branches:
      - main

jobs:
  upload-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24'

      - name: Generate coverage report
        run: go test -coverprofile="coverage.txt" $(go list ./... | grep -v '/examples\|/mock')

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}